development:
  adapter: postgresql
  database: data_exchange_development
  host: localhost

test:
    adapter: postgresql
    database: data_exchange_test
    host: localhost


production:
    adapter: postgresql
    database: data_exchange_production
    host: localhost
